/*
 * This file is generated by jOOQ.
*/
package com.shelajev.rebellabs.report2017.analysisapp.model;


import com.shelajev.rebellabs.report2017.analysisapp.model.tables.Results;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.RESULTS</code>.
     */
    public static final Results RESULTS = com.shelajev.rebellabs.report2017.analysisapp.model.tables.Results.RESULTS;
}
